[mqtt]
  [mqtt.broker]
  url = "tcp://142.93.118.47:1883"

  [mqtt.message]
  size = 200
  format = "text"
  qos = 2
  retain = false
  payload = "{\"n\":\"lon\",\"t\":-4,\"v\":1.3}"

  [mqtt.tls]
  mtls = false
  skiptlsver = true
  ca = "ca.crt"

[test]
pubs = 100
subs = 30
count = 100
count =5 

[log]
quiet = false

[mainflux]
connections_file = "../provision/mfconn.toml"
