###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3.7"

  
services:
  mfxkit:
    container_name: mainflux-mfxkit
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 9021:9021
    environment:
      MF_MFXKIT_LOG_LEVEL: 'debug'
      MF_MFXKIT_HTTP_PORT: 9021
      MF_MFXKIT_SERVER_CERT: ''
      MF_MFXKIT_SERVER_KEY: ''
      MF_JAEGER_URL: ''
      MF_MFXKIT_SECRET: 'secret'
