###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "2"

services:
  ###
  # NATS
  ###
  nats:
    image: nats:latest
    container_name: mainflux-nats
    ports:
      - "4222:4222"
      - "8222:8222"
  
  ###
  # Cassandra clusters
  ###
  cassandra:
    image: cassandra:latest
    container_name: mainflux-cassandra
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes:
      - ./cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mainflux_cluster
      - CASSANDRA_SEEDS=cassandra
  
  cassandra_1:
    image: cassandra:latest
    container_name: mainflux-cassandra_1
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes:
      - ./cassandra_1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mainflux_cluster
      - CASSANDRA_SEEDS=cassandra
    depends_on:
      - cassandra

  cassandra_2:
    image: cassandra:latest
    container_name: mainflux-cassandra_2
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f'
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes:
      - ./cassandra_2:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mainflux_cluster
      - CASSANDRA_SEEDS=cassandra
    depends_on:
      - cassandra
      - cassandra_1

  ###
  # Manager
  ###
  manager:
    image: mainflux/manager:latest
    container_name: mainflux-manager
    ports:
      - "8180:8180"
      - "9090:9090"
    depends_on:
      - cassandra
      - cassandra_1
      - cassandra_2
    environment:
      - MANAGER_DB_CLUSTER=cassandra,cassandra_1,cassandra_2
      - MANAGER_DB_KEYSPACE=system_distributed


  ###
  # Message Writer
  ###
  message-writer:
    image: mainflux/message-writer:latest
    container_name: mainflux-message-writer
    depends_on:
      - cassandra
      - cassandra_1
      - cassandra_2
    environment:
      - MESSAGE_WRITER_DB_CLUSTER=cassandra,cassandra_1,cassandra_2
      - MESSAGE_WRITER_DB_KEYSPACE=system_distributed
      - MESSAGE_WRITER_NATS_URL=nats://nats:4222
  
  ###
  # MQTT Broker
  ###
  mqtt-adapter:
    image: mainflux/mqtt-adapter:latest
    container_name: mainflux-mqtt
    ports:
      - "1883:1883"
      - "8883:8883"

  ###
  # CoAP Server
  ###
  mainflux-coap:
    image: mainflux/coap-adapter:latest
    container_name: mainflux-coap
    ports:
      - "5683:5683"

  ###
  # HTTP Server
  ###
  http-adapter:
    image: mainflux/http-adapter:latest
    container_name: mainflux-http
    depends_on:
      - nats
    environment:
      - HTTP_ADAPTER_NATS_URL=nats://nats:4222
    ports:
      - "7070:7070"

