apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: manager
  labels:
    component: manager
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: manager
    spec:
      containers:
      - name: mainflux-manager
        image: mainflux/manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8180
        env:
        - name: MF_DB_HOST
          value: "mainflux-postgres"
        - name: MF_MANAGER_DB
          value: "mainflux"
        - name: MF_MANAGER_PORT
          value: "8180"
        - name: MF_MANAGER_SECRET
          value: "test-secret"

