###
# This docker-compose file contains optional opc-adapter and opc-redis services
# for the Mainflux platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.
###

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

services:
  opc-redis:
    image: redis:5.0-alpine
    container_name: mainflux-opc-redis
    restart: on-failure
    networks:
      - docker_mainflux-base-net

  opc-adapter:
    image: mainflux/opc-amd64:latest
    container_name: mainflux-opc
    restart: on-failure
    environment:
      MF_OPC_ADAPTER_LOG_LEVEL: ${MF_OPC_ADAPTER_LOG_LEVEL}
      MF_THINGS_ES_URL: es-redis:${MF_REDIS_TCP_PORT}
      MF_OPC_ADAPTER_ROUTEMAP_URL: opc-redis:${MF_REDIS_TCP_PORT}
      MF_OPC_ADAPTER_HTTP_PORT: ${MF_OPC_ADAPTER_HTTP_PORT}
      MF_NATS_URL: ${MF_NATS_URL}
    ports:
      - ${MF_OPC_ADAPTER_HTTP_PORT}:${MF_OPC_ADAPTER_HTTP_PORT}
    networks:
      - docker_mainflux-base-net
