apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-balancer
  annotations:
    ingress.kubernetes.io/ssl-redirect: “false”
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  # tls:
  #   - secretName: tls-certificate
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: dashflux
          servicePort: 80
      - path: /token/
        backend:
          serviceName: manager
          servicePort: 8180

