apiVersion: v1
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 1883
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: adapter-mqtt
              # access_log:
              #   - name: envoy.file_access_log
              #     config:
              #       path: /dev/stdout
      clusters:
      - name: adapter-mqtt
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: {{ .Release.Name }}-adapter-mqtt
            port_value: 1883
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-envoy-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: envoy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: envoy
    spec:
      containers:
        - image: envoyproxy/envoy:v1.12.1
          imagePullPolicy: Always
          name: {{ .Release.Name }}-envoy
          ports:
            - containerPort: 1883 
              protocol: TCP
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              name: envoy-config
              subPath: envoy.yaml
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-envoy-config
            optional: false
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  selector:
    app: {{ .Release.Name }}
    component: envoy
  ports:
    - port: 1883
      protocol: TCP
      name: mqtt
    - port: 8001
      protocol: TCP
      name: admin
