apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: coap-adapter
    spec:
      containers:
      - name: mainflux-coap
        image: mainflux/coap
        imagePullPolicy: Always
        ports:
        - containerPort: 5683
        env:
        - name: COAP_ADAPTER_NATS_URL
          value: "nats://nats:4222"

