apiVersion: v1
kind: Service
metadata:
  name: coap-adapter
  labels:
    component: coap-adapter
spec:
  selector:
    component: coap-adapter
  ports:
  - protocol: UDP
    port: 5683
    targetPort: 5683
  type: LoadBalancer
