###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3"

services:
  # nginx:
  #   image: nginx:1.13-alpine
  #   container_name: mainflux-nginx
  #   restart:
  #     on-failure
  #   volumes:
  #     - $PWD/nginx.conf:/etc/nginx/nginx.conf
  #     - $PWD/ssl/certs/mainflux-server.crt:/etc/ssl/certs/mainflux-server.crt
  #     - $PWD/ssl/certs/mainflux-server.key:/etc/ssl/private/mainflux-server.key
  #     - $PWD/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "8883:8883"

  nats:
    image: nats:1.0.2
    container_name: mainflux-nats
    restart:
      on-failure

  postgres:
    image: postgres:10.2-alpine
    container_name: mainflux-postgres
    restart:
      on-failure
    ports:
        - 5432:5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  normalizer:
    image: mainflux/normalizer:latest
    container_name: mainflux-normalizer
    restart:
      on-failure
    expose:
      - 8181
    environment:
      MF_NATS_URL: nats://nats:4222
      MF_NORMALIZER_PORT: 8181

  http-adapter:
    image: mainflux/http:latest
    container_name: mainflux-http
    depends_on:
      - clients
    restart:
      on-failure
    expose:
      - 8184
    environment:
      MF_CLIENTS_URL: http://clients:8183
      MF_NATS_URL: nats://nats:4222
      MF_HTTP_ADAPTER_PORT: 8184
    ports:
      - 8184:8184

  clients:
    image: mainflux/clients:latest
    container_name: mainflux-clients
    expose:
      - 8182
      - 8183
    restart:
      on-failure
    environment:
      MF_CLIENTS_DB_HOST: postgres
      MF_CLIENTS_DB_PORT: 5432
      MF_CLIENTS_DB_USER: mainflux
      MF_CLIENTS_DB_PASS: mainflux
      MF_CLIENTS_DB: clients
      MF_CLIENTS_HTTP_PORT: 8182
      MF_CLIENTS_GRPC_PORT: 8183
      MF_USERS_URL: users
      MF_CLIENTS_SECRET: clients

  users:
    image: mainflux/users:latest
    container_name: mainflux-users
    expose:
      - 8180
      - 8181
    restart:
      on-failure
    environment:
      MF_USERS_DB_HOST: postgres
      MF_USERS_DB_PORT: 5432
      MF_USERS_DB_USER: mainflux
      MF_USERS_DB_PASS: mainflux
      MF_USERS_DB: users
      MF_USERS_HTTP_PORT: 8180
      MF_USERS_GRPC_PORT: 8181
      MF_USERS_SECRET: users
    ports:
      - 80:8180

  coap:
    image: mainflux/coap:latest
    container_name: mainflux-coap
    expose:
      - 5683
    restart:
      on-failure
    environment:
      MF_COAP_ADAPTER_PORT: 5683
      MF_NATS_URL: nats://nats:4222
      MF_CLIENTS_URL: clients
    ports:
      - 5683:5683

  ws:
    image: mainflux/ws:latest
    container_name: mainflux-ws
    expose:
      - 8185
    restart:
      on-failure
    environment:
      MF_WS_ADAPTER_PORT: 8185
      MF_NATS_URL: nats://nats:4222
      MF_CLIENTS_URL: clients
    ports:
      - 8185:8185
