apiVersion: v1
kind: Service
metadata:
  name: http-adapter
  labels:
    component: http-adapter
spec:
  selector:
    component: http-adapter
  ports:
  - port: 8182
    targetPort: 8182
  type: LoadBalancer
