###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

# MQTT
mqttHost = '0.0.0.0'
mqttPort = 1883
mqttWsPort = 8883
