apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.dashflux.name }}
  labels:
    component: dashflux
spec:
  template:
    metadata:
      labels:
        component: {{ .Values.dashflux.name }}
    spec:
      containers:
      - name: dashflux
        image: {{ .Values.dashfluxImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.dashflux.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dashflux.name }}
  labels:
    component: {{ .Values.dashflux.name }}
spec:
  selector:
    component: {{ .Values.dashflux.name }}
  ports:
  - port: {{ .Values.dashflux.port }}
  # type: LoadBalancer
