apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.normalizer.name }}
  labels:
    component: {{ .Values.normalizer.name }}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: {{ .Values.normalizer.name }}
    spec:
      containers:
      - name: {{ .Values.normalizer.name }}
        image: {{ .Values.normalizerImage }}
        imagePullPolicy: Always
        env:
        {{- range $key, $value := .Values.adapter.http.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
#        - name: MF_NATS_URL
#          value: "nats://nats:4222"
#        - name: MF_NORMALIZER_PORT
#          value: "8184"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.normalizer.name }}
  labels:
    component: {{ .Values.normalizer.name }}
spec:
  selector:
    component: {{ .Values.normalizer.name }}
  ports:
  - port: {{ .Values.normalizer.port }}
  clusterIP: None
