apiVersion: v1
kind: PersistentVolume
metadata:
  name: mainflux-users-postgres-data-disk
  labels:
    name: mainflux-users-postgres-data-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/users-postgres-0
  persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mainflux-users-postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.users-db.name }}
  labels:
    name: {{ .Values.users-db.name }}
spec:
  containers:
    - name: {{ .Values.users-db.name }}
      image: {{ .Values.usersPostgresImage }}
      env:
        - name: POSTGRES_USER
          value: "mainflux"
        - name: POSTGRES_PASSWORD
          value: "mainflux"
        - name: POSTGRES_DB
          value: "users"
        - name: PGDATA
          value: /var/lib/postgresql/data/mainflux-users-postgres-data
      ports:
        - containerPort: 5432
      resources:
{{ toYaml .Values.defaultResources | indent 8 }}
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: mainflux-users-postgres-data
  volumes:
    - name: mainflux-users-postgres-data
      persistentVolumeClaim:
        claimName: mainflux-users-postgres-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.users-db.name }}
  labels:
    name: {{ .Values.users-db.name }}
spec:
  ports:
    - port: {{ .Values.users-db.container_ports.db-port }}
  selector:
    name: {{ .Values.users-db.name }}
