swagger: "2.0"
info:
  title: Mainflux WebSocket adapter
  description: WebSocket standard handshake over HTTP.
  version: "1.0.0"
paths:
  /channels/{id}/messages:
    get:
      summary: Creates WebSocket connection
      description: |
        Creates and opens WebSocket connection for specific channel.
      tags:
        - messages
      consumes:
        - "application/senml+json"
        - "text/plain"
      produces: []
      parameters:
        - name: auth
          description: Access token.
          in: query
          type: string
          required: true
        - name: id
          description: Unique channel identifier.
          in: path
          type: string
          format: uuid
          required: true
      responses:
        101:
          description: Switching protocol from HTTP to WebSocket.
        401:
          description: |
            Message discarded due to missing or invalid token, or unauthorized 
            access to the channel.
        500:
          description: Unexpected server-side error occured.
