apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: normalizer
  labels:
    component: normalizer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: normalizer
      containers:
      - name: mainflux-normalizer
        image: mainflux/normalizer:latest
        imagePullPolicy: Always
        env:
        - name: MF_NATS_URL
          value: "nats://nats:4222"
        - name: MF_NORMALIZER_PORT
          value: "8181"
