apiVersion: v1
kind: Service
metadata:
  name: normalizer
  labels:
    component: normalizer
spec:
  selector:
    component: normalizer
  ports:
  - port: 8181
    targetPort: 8181
  clusterIP: None
