apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb-writer
  labels:
    component: mongodb-writer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: mongodb-writer
    spec:
      containers:
      - name: mainflux-mongodb-writer
        image: juanman/mongodb-writer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8901
        env:
          - name: MF_MONGO_WRITER_LOG_LEVEL
            value: "debug"
          - name: MF_NATS_URL
            value: "nats://nats:4222"
          - name: MF_MONGO_WRITER_PORT
            value: "8901"
          - name: MF_MONGO_WRITER_DB_NAME
            value: "mainflux"
          - name: MF_MONGO_WRITER_DB_HOST
            value: "mainflux-mongodb"
          - name: MF_MONGO_WRITER_DB_PORT
            value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-writer
  labels:
    component: mongodb-writer
spec:
  selector:
    component: mongodb-writer
  ports:
  - port: 8901
  # type: LoadBalancer
