apiVersion: v1
kind: Service
metadata:
  name: mqtt-adapter
  labels:
    component: mqtt-adapter
spec:
  selector:
    component: mqtt-adapter
  ports:
  - port: 1883
    targetPort: 1883
  type: LoadBalancer
